#!/usr/bin/env node
/**
 * Fetches category colour data from eolas and writes the generated CSS file
 * used by lucos-search.js.  Run automatically as the first step of `npm run build`.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = join(__dirname, '..', 'web-components', 'generated', 'category-colours.css');
const EOLAS_URL = 'https://eolas.l42.eu/metadata/categories.json';

async function main() {
	console.log(`Fetching category colours from ${EOLAS_URL} ...`);
	const response = await fetch(EOLAS_URL);
	if (!response.ok) {
		throw new Error(`Failed to fetch category colours: HTTP ${response.status}`);
	}
	const categories = await response.json();

	const cssLines = [
		'/* Generated by scripts/generate-colours.js — do not edit by hand */',
		'/* Run `npm run build` to regenerate from the eolas categories endpoint */',
		'',
	];

	for (const { name, background, border, text } of categories) {
		cssLines.push(`.lozenge[data-category="${name}"] {`);
		cssLines.push(`\t--lozenge-background: ${background};`);
		cssLines.push(`\t--lozenge-border: ${border};`);
		cssLines.push(`\t--lozenge-text: ${text};`);
		cssLines.push('}');
		cssLines.push('');
	}

	mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
	writeFileSync(OUTPUT_FILE, cssLines.join('\n'));
	console.log(`Written ${OUTPUT_FILE} (${categories.length} categories)`);
}

main().catch(err => {
	console.error(`Error generating category colours: ${err.message}`);
	process.exit(1);
});
